### ISSUE TITLE
[bug]当编辑的时候头部只渲染一行商品规格

### ISSUE THREAD

**Issue by taobali32** [Abbotton/dcat-sku-plus#2]
编辑的时候头部规格尺码不显示
![image](https://user-images.githubusercontent.com/30717763/147224260-da714186-0e5a-41bb-a944-80e2ce8c0b51.png)

我的代码

这三种无论如何给都不行
![image](https://user-images.githubusercontent.com/30717763/147224343-a91818f3-46cd-4870-85b4-34158edaaaba.png)

数据库存储的
![image](https://user-images.githubusercontent.com/30717763/147224414-0179dc5e-6426-4b2b-8942-1ddb4c0c254a.png)

**Comment by taobali32** [comment]
已解决，根据dcat-easy-sku.js 110行中
![image](https://user-images.githubusercontent.com/30717763/147228470-77389b73-fcdd-4c79-8a5f-2a04e0bae0e8.png)


具体修复index.js  109行

![image](https://user-images.githubusercontent.com/30717763/147228535-05ada33e-6228-480a-b9f4-5c19d3be31ab.png)


```
               if (index >= 1) {
                    var html = _this.getHtml();
                    _this.wrap.find('.sku_attr_key_val tbody').append(html);
                }

                let tr = tbody.find('tr').eq(index);

**Comment by Abbotton** [comment]
欢迎提交PR 🤝
